const DIFFICULTY = 3;
const STARTING_BALANCE = 100;
const DIVIDEND = 20;
const REWARD = 50;
const IP_BOOTSTRAP = '127.0.0.1';
const IP_PEER = '127.0.0.1';

module.exports = {
  DIFFICULTY,
  STARTING_BALANCE,
  DIVIDEND,
  REWARD,
  IP_BOOTSTRAP,
  IP_PEER,
};
